### ISSUE TITLE
Is there a reason you use "new" rather than "::create" in the example? 

### ISSUE THREAD

**Issue by sunnysideup** [sminnee/silverstripe-verbosefields#2]
Just curious ... I always use ::create, but maybe this is wrong ...

**Comment by sminnee** [comment]
::create was necessary in earlier versions of PHP, where you couldn't chain methods off new.

Now that `(new X)->something()` works (I can't recall if it was 7.1, 7.2, or 7.3 that allowed this), I prefer to use that, as it doesn't rely on the create method existing.
